### PR TITLE
Delete `compiled command:` message

### PR DESCRIPTION
**Pull request by dikey0ficial**
it interferes.

### CODE REVIEW

**Comment by alexg-axis** [comment]
The workaround I've used is simply disabling the builtin log package as I use another package.

```go
// Not ideal, but the ffmpeg library uses log.Printf to print the "compiled"
// ffmpeg command before executing it. Don't print it.
log.SetOutput(ioutil.Discard)
```

**Comment by u2takey** [comment]
> it interferes.

looks fine to me! But would you please resolve conflict first? tks!

**Comment by martinwang2002** [comment]
https://github.com/u2takey/ffmpeg-go/blob/8af5c3849807dcda756406a7b2b3631a5c90d53b/run.go#L7
https://github.com/u2takey/ffmpeg-go/blob/8af5c3849807dcda756406a7b2b3631a5c90d53b/run.go#L267

I think it's just removing two lines.

**Comment by dikey0ficial** [comment]
> > it interferes.
> 
> looks fine to me! But would you please resolve conflict first? tks!

resolved ;)

**Comment by aitchkhan** [comment]
can we get this merged?

**Pull request closed without merging**
